### ISSUE TITLE
IOS Problem

### ISSUE THREAD

**Issue by hazemosama** [mehranshoqi/voice_message_player#39]
Package is not running on IOS, its displayed on screen but not playing audio.

**Comment by ghost** [comment]
Getting this error on IOS Device 

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: (-1102) You do not have permission to access the requested resource.
```
#0      AudioPlayer._load (package:just_audio/just_audio.dart:869:9)
<asynchronous suspension>
#1      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1464:28)
<asynchronous suspension>
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: (-1102) You do not have permission to access the requested resource.
#0      AudioPlayer._load (package:just_audio/just_audio.dart:869:9)
<asynchronous suspension>
#1      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1464:28)
<asynchronous suspension>
```

**Comment by YoussefAbdelmonem** [comment]
I got the same error in ios but it works fine in android

**Comment by hazemosama** [comment]
@YoussefAbdelmonem  I've sent you a connection request on LinkedIn. contact me to give you a solution.

**Comment by Saydaleivs** [comment]
> @YoussefAbdelmonem I've sent you a connection request on LinkedIn. contact me to give you a solution.

Can you please give me the solution too?
