### ISSUE TITLE
Error initializing AudioTrack

### ISSUE THREAD

**Issue by AbdullahLabib22** [mehranshoqi/voice_message_player#4]
When I dispose from the screen that contains the VoiceMessage widget and enter again it throw that error:

```
E/AudioTrack-JNI( 8854): Error -12 initializing AudioTrack
E/android.media.AudioTrack( 8854): Error code -20 when initializing AudioTrack.
E/MediaCodecAudioRenderer( 8854): Audio sink error
E/MediaCodecAudioRenderer( 8854):   com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(16000, 4, 8000)
E/MediaCodecAudioRenderer( 8854):       at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2222)
E/MediaCodecAudioRenderer( 8854):       at com.google.android.exoplayer2.audio.DefaultAudioSink.buildAudioTrack(DefaultAudioSink.java:1053)
E/MediaCodecAudioRenderer( 8854):       at com.google.android.exoplayer2.audio.DefaultAudioSink.buildAudioTrackWithRetry(DefaultAudioSink.java:1032)
E/MediaCodecAudioRenderer( 8854):       at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:836)
E/MediaCodecAudioRenderer( 8854):       at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:915)
E/MediaCodecAudioRenderer( 8854):       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:703)
E/MediaCodecAudioRenderer( 8854):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1881)
E/MediaCodecAudioRenderer( 8854):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:792)
E/MediaCodecAudioRenderer( 8854):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)
E/MediaCodecAudioRenderer( 8854):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)
E/MediaCodecAudioRenderer( 8854):       at android.os.Handler.dispatchMessage(Handler.java:101)
E/MediaCodecAudioRenderer( 8854):       at android.os.Looper.loop(Looper.java:156)
E/MediaCodecAudioRenderer( 8854):       at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 8854): Playback error
E/ExoPlayerImplInternal( 8854):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(null, null, null, audio/raw, null, -1, null, [-1, -1, -1.0], [1, 16000]), format_supported=YES
E/ExoPlayerImplInternal( 8854):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:575)
E/ExoPlayerImplInternal( 8854):       at android.os.Handler.dispatchMessage(Handler.java:101)
E/ExoPlayerImplInternal( 8854):       at android.os.Looper.loop(Looper.java:156)
E/ExoPlayerImplInternal( 8854):       at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 8854):   Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(16000, 4, 8000)
E/ExoPlayerImplInternal( 8854):       at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2222)
E/ExoPlayerImplInternal( 8854):       at com.google.android.exoplayer2.audio.DefaultAudioSink.buildAudioTrack(DefaultAudioSink.java:1053)
E/ExoPlayerImplInternal( 8854):       at com.google.android.exoplayer2.audio.DefaultAudioSink.buildAudioTrackWithRetry(DefaultAudioSink.java:1032)
E/ExoPlayerImplInternal( 8854):       at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:836)
E/ExoPlayerImplInternal( 8854):       at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:915)
E/ExoPlayerImplInternal( 8854):       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:703)
E/ExoPlayerImplInternal( 8854):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1881)
E/ExoPlayerImplInternal( 8854):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:792)
E/ExoPlayerImplInternal( 8854):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)
E/ExoPlayerImplInternal( 8854):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)
E/ExoPlayerImplInternal( 8854):       ... 3 more
 ```

**Comment by Ahmed-Tarek-Designfy** [comment]
Why is this issue closed? I still get the same error: E/AudioPlayer(15931): TYPE_RENDERER: AudioTrack init failed 0 Config(16000, 4, 10304) Format(null, null, null, audio/raw, null, -1, null, [-1, -1, -1.0], [1, 16000])

The case for me is when I go to the gallery to attach an image and try to play the voice again it gives me that error and then the voice plays without sound.

If this error happens once, the issue exists even when I close the screen and return to it again, all the voices in the app give the same error and play without sound. The only way this error goes away is to reload the app.

**Comment by igorfastronicorrea** [comment]
> Why is this issue closed? I still get the same error: E/AudioPlayer(15931): TYPE_RENDERER: AudioTrack init failed 0 Config(16000, 4, 10304) Format(null, null, null, audio/raw, null, -1, null, [-1, -1, -1.0], [1, 16000])
> 
> The case for me is when I go to the gallery to attach an image and try to play the voice again it gives me that error and then the voice plays without sound.
> 
> If this error happens once, the issue exists even when I close the screen and return to it again, all the voices in the app give the same error and play without sound. The only way this error goes away is to reload the app.

I have this bug, do you can fix this?
